(add-to-list 'load-path "~/.emacs.d/custom")
(load "my-package.el")
(load "my-common-setup.el")
(load "my-auto-complete.el")
(load "my-emmet-mode.el")
(load "my-clojure.el")
(load "my-web.el")
(load "my-haskell.el")
(load "my-groovy.el")
(load "my-scheme.el")
(load "my-org.el")
(load "my-others.el")

